// products.js - Complete product database
const products = [
    // ===== FASHION - T-SHIRTS =====
    {
        id: 1,
        name: "Demon Slayer Tanjiro Kamado T-Shirt",
        price: 1299,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/T-Shirt/Demon Slayer Tanjiro Kamado T-Shirt.png",
        rating: 4.8,
        reviews: 234,
        description: "High-quality cotton t-shirt featuring Tanjiro from Demon Slayer",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 2,
        name: "Naruto Shippuden Sage Mode T-Shirt",
        price: 1199,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/T-Shirt/Naruto Shippuden Sage Mode T-Shirt.png",
        rating: 4.9,
        reviews: 567,
        description: "Naruto Uzumaki in Sage Mode design",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 3,
        name: "One Piece Luffy Gear 5 T-Shirt",
        price: 1499,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/T-Shirt/One Piece Luffy Gear 5 T-Shirt.png",
        rating: 5.0,
        reviews: 123,
        description: "Celebrate Gear 5 with this exclusive design",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 4,
        name: "Jujutsu Kaisen Gojo Satoru T-Shirt",
        price: 1399,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/T-Shirt/Jujutsu Kaisen Gojo Satoru T-Shirt.png",
        rating: 4.7,
        reviews: 345,
        description: "Premium t-shirt with Gojo's iconic look",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: false
    },
    {
        id: 5,
        name: "Attack on Titan Eren Yeager T-Shirt",
        price: 1299,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/aot-hoodie-1.png",
        rating: 4.8,
        reviews: 189,
        description: "Survey Corps design with Eren",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: false
    },
    {
        id: 6,
        name: "Dragon Ball Z Goku Ultra Instinct T-Shirt",
        price: 1399,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/T-Shirt/Dragon Ball Z Goku Ultra Instinct T-Shirt.png",
        rating: 4.9,
        reviews: 456,
        description: "Goku in Ultra Instinct form",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 21,
        name: "Blue Lock Isagi Yoichi T-Shirt",
        price: 1399,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/T-Shirt/Blue Lock Isagi Yoichi T-Shirt.png",
        rating: 4.8,
        reviews: 120,
        description: "Striker ego design featuring Isagi Yoichi",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 22,
        name: "Black Clover Asta Anti Magic T-Shirt",
        price: 1499,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/T-Shirt/Black Clover Asta Anti Magic T-Shirt.png",
        rating: 4.9,
        reviews: 210,
        description: "Asta with anti-magic sword design",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 23,
        name: "Solo Leveling Sung Jin-Woo Shadow T-Shirt",
        price: 1599,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/T-Shirt/Solo Leveling Sung Jin-Woo Shadow T-Shirt.png",
        rating: 5.0,
        reviews: 300,
        description: "Shadow Monarch Jin-Woo design",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 24,
        name: "Bleach Ichigo Kurosaki Bankai T-Shirt",
        price: 1399,
        category: "fashion",
        subCategory: "tshirt",
        type: "T-Shirt",
        image: "assets/images/products/T-Shirt/Bleach Ichigo Kurosaki Bankai T-Shirt.png",
        rating: 4.8,
        reviews: 180,
        description: "Ichigo Bankai form design",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },

    // ===== FASHION - HOODIES =====
    {
        id: 7,
        name: "Demon Slayer Akaza Hoodie",
        price: 2499,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/Demon Slayer Akaza Hoodie.png",
        rating: 4.8,
        reviews: 278,
        description: "Premium hoodie featuring Akaza from Demon Slayer",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 8,
        name: "Naruto Akatsuki Cloud Hoodie",
        price: 2399,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/Naruto Akatsuki Cloud Hoodie.png",
        rating: 4.8,
        reviews: 456,
        description: "Akatsuki cloud design hoodie",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: false
    },
    {
        id: 9,
        name: "Attack on Titan Scout Regiment Hoodie",
        price: 2599,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/Attack on Titan Scout Regiment Hoodie.png",
        rating: 4.9,
        reviews: 189,
        description: "Wings of Freedom design",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 10,
        name: "Jujutsu Kaisen Sukuna Hoodie",
        price: 2699,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/Jujutsu Kaisen Sukuna Hoodie.png",
        rating: 4.7,
        reviews: 234,
        description: "King of Curses design",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: false
    },
    {
        id: 11,
        name: "One Piece Straw Hat Pirates Hoodie",
        price: 2499,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/One Piece Straw Hat Pirates Hoodie.png",
        rating: 4.9,
        reviews: 345,
        description: "Straw Hat Jolly Roger design",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 12,
        name: "Dragon Ball Z Super Saiyan Hoodie",
        price: 2799,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/Dragon Ball Z Super Saiyan Hoodie.png",
        rating: 4.8,
        reviews: 567,
        description: "Super Saiyan transformation design",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 25,
        name: "Blue Lock Ego Striker Hoodie",
        price: 2599,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/Blue Lock Ego Striker Hoodie.png",
        rating: 4.7,
        reviews: 90,
        description: "Blue Lock striker themed hoodie",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: false
    },
    {
        id: 26,
        name: "Black Clover Black Bulls Hoodie",
        price: 2699,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/Black Clover Black Bulls Hoodie.png",
        rating: 4.9,
        reviews: 140,
        description: "Black Bulls squad hoodie",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 27,
        name: "Solo Leveling Shadow Army Hoodie",
        price: 2799,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/Solo Leveling Shadow Army Hoodie.png",
        rating: 5.0,
        reviews: 200,
        description: "Shadow army aesthetic hoodie",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: true
    },
    {
        id: 28,
        name: "Bleach Soul Reaper Hoodie",
        price: 2599,
        category: "fashion",
        subCategory: "hoodie",
        type: "Hoodie",
        image: "assets/images/products/hoodies/Bleach Soul Reaper Hoodie.png",
        rating: 4.8,
        reviews: 160,
        description: "Soul Reaper uniform style hoodie",
        sizes: ["S", "M", "L", "XL"],
        inStock: true,
        featured: false
    },

    // ===== WATCHES =====
    {
        id: 13,
        name: "Dragon Ball Z Chronograph Watch",
        price: 3499,
        category: "watches",
        image: "assets/images/watches/Dragon Ball Z Chronograph Watch.png",
        rating: 4.6,
        reviews: 89,
        description: "Official Dragon Ball Z chronograph watch",
        inStock: true,
        featured: true
    },
    {
        id: 14,
        name: "Naruto Akatsuki Cloud Watch",
        price: 2999,
        category: "watches",
        image: "assets/images/watches/Naruto Akatsuki Cloud Watch.png",
        rating: 4.7,
        reviews: 145,
        description: "Akatsuki cloud design analog watch",
        inStock: true,
        featured: true
    },
    {
        id: 15,
        name: "One Piece Pirate King Watch",
        price: 3999,
        category: "watches",
        image: "assets/images/watches/One Piece Pirate King Watch.png",
        rating: 4.8,
        reviews: 67,
        description: "Limited edition Pirate King watch",
        inStock: true,
        featured: false
    },
    {
        id: 16,
        name: "Demon Slayer Clockwork Watch",
        price: 3299,
        category: "watches",
        image: "assets/images/watches/Demon Slayer Clockwork Watch.png",
        rating: 4.5,
        reviews: 34,
        description: "Demon Slayer themed mechanical watch",
        inStock: true,
        featured: false
    },
    {
        id: 29,
        name: "Blue Lock Egoist Striker Watch",
        price: 3499,
        category: "watches",
        image: "assets/images/watches/Blue Lock Egoist Striker Watch.png",
        rating: 4.7,
        reviews: 110,
        description: "Blue Lock striker ego themed watch",
        inStock: true,
        featured: true
    },
    {
        id: 30,
        name: "Black Clover Magic Knight Watch",
        price: 3299,
        category: "watches",
        image: "assets/images/watches/Black Clover Magic Knight Watch.png",
        rating: 4.8,
        reviews: 150,
        description: "Magic Knight squad inspired watch",
        inStock: true,
        featured: true
    },
    {
        id: 31,
        name: "Solo Leveling Shadow Monarch Watch",
        price: 3799,
        category: "watches",
        image: "assets/images/watches/Solo Leveling Shadow Monarch Watch.png",
        rating: 5.0,
        reviews: 200,
        description: "Shadow Monarch premium watch design",
        inStock: true,
        featured: true
    },
    {
        id: 32,
        name: "Bleach Soul Reaper Bankai Watch",
        price: 3599,
        category: "watches",
        image: "assets/images/watches/Bleach Soul Reaper Bankai Watch.png",
        rating: 4.9,
        reviews: 175,
        description: "Bankai inspired luxury anime watch",
        inStock: true,
        featured: false
    },

    // ===== BAGS =====
    {
        id: 17,
        name: "Pikachu Electric Backpack",
        price: 1899,
        category: "bags",
        image: "assets/images/bags/Pikachu Electric Backpack.jpg",
        rating: 4.8,
        reviews: 234,
        description: "Pikachu face backpack with electric details",
        inStock: true,
        featured: true
    },
    {
        id: 18,
        name: "Naruto Ninja Messenger Bag",
        price: 1599,
        category: "bags",
        image: "assets/images/bags/Naruto Ninja Messenger Bag.png",
        rating: 4.7,
        reviews: 178,
        description: "Hidden Leaf Village messenger bag",
        inStock: true,
        featured: true
    },
    {
        id: 19,
        name: "Attack on Titan Survey Corps Backpack",
        price: 2199,
        category: "bags",
        image: "assets/images/bags/Attack on Titan Survey Corps Backpack.png",
        rating: 4.9,
        reviews: 145,
        description: "Survey Corps emblem backpack",
        inStock: true,
        featured: false
    },
    {
        id: 20,
        name: "Demon Slayer Kimetsu Bag",
        price: 1799,
        category: "bags",
        image: "assets/images/bags/Demon Slayer Kimetsu Bag.png",
        rating: 4.6,
        reviews: 89,
        description: "Demon Slayer pattern backpack",
        inStock: true,
        featured: true
    },
    {
        id: 33,
        name: "Blue Lock Ego Striker Backpack",
        price: 1999,
        category: "bags",
        image: "assets/images/bags/Blue Lock Ego Striker Backpack.png",
        rating: 4.7,
        reviews: 120,
        description: "Blue Lock striker themed backpack",
        inStock: true,
        featured: true
    },
    {
        id: 34,
        name: "Black Clover Black Bulls Backpack",
        price: 1899,
        category: "bags",
        image: "assets/images/bags/Black Clover Black Bulls Backpack.png",
        rating: 4.8,
        reviews: 150,
        description: "Black Bulls squad logo backpack",
        inStock: true,
        featured: true
    },
    {
        id: 35,
        name: "Solo Leveling Shadow Army Backpack",
        price: 2199,
        category: "bags",
        image: "assets/images/bags/Solo Leveling Shadow Army Backpack.png",
        rating: 5.0,
        reviews: 180,
        description: "Shadow army aesthetic backpack",
        inStock: true,
        featured: true
    },
    {
        id: 36,
        name: "Bleach Soul Reaper Backpack",
        price: 1999,
        category: "bags",
        image: "assets/images/bags/Bleach Soul Reaper Backpack.png",
        rating: 4.9,
        reviews: 140,
        description: "Soul Reaper uniform themed backpack",
        inStock: true,
        featured: false
    }
];

// Make products globally available
window.products = products;